x-common-vars: &common-vars
  env_file:
    - .env

services:
  postgres:
    <<: *common-vars
    image: postgres:16-alpine
    container_name: plantio-postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${IDENTITY_DB},${PLANTS_DB},${FEED_DB},${GATEWAY_DB},${NOTIFICATIONS_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres-init-multiple-dbs.sh:/docker-entrypoint-initdb.d/00-create-multiple-dbs.sh:ro
    ports:
      - "5432:5432"

  rabbitmq:
    <<: *common-vars
    image: rabbitmq:3-management-alpine
    container_name: plantio-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

  api-gateway:
    <<: *common-vars
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - identity-service
      - plants-service
      - feed-service
      - notifications-service
    command:
      - /run/APIGateway
      - serve
      - --env
      - production
      - --hostname
      - 0.0.0.0
      - --port
      - "3000"
    environment:
      DATABASE_NAME: ${GATEWAY_DB}
      IDENTITY_SERVICE_URL: http://identity-service:3001
      PLANTS_SERVICE_URL: http://plants-service:3002
      FEED_SERVICE_URL: http://feed-service:3003
      NOTIFICATIONS_SERVICE_URL: http://notifications-service:3004
    ports:
      - "${API_GATEWAY_PORT}:3000"

  identity-service:
    <<: *common-vars
    build:
      context: ./services/identity-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    command:
      - /run/IdentityService
      - serve
      - --env
      - production
      - --hostname
      - 0.0.0.0
      - --port
      - "3001"
    environment:
      DATABASE_NAME: ${IDENTITY_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672${RABBITMQ_VHOST}
      SERVICE_PORT: ${IDENTITY_SERVICE_PORT}
    ports:
      - "${IDENTITY_SERVICE_PORT}:3001"

  plants-service:
    <<: *common-vars
    build:
      context: ./services/plants-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    command:
      - /run/PlantsService
      - serve
      - --env
      - production
      - --hostname
      - 0.0.0.0
      - --port
      - "3002"
    environment:
      DATABASE_NAME: ${PLANTS_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672${RABBITMQ_VHOST}
      SERVICE_PORT: ${PLANTS_SERVICE_PORT}
    ports:
      - "${PLANTS_SERVICE_PORT}:3002"

  feed-service:
    <<: *common-vars
    build:
      context: ./services/feed-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    command:
      - /run/FeedService
      - serve
      - --env
      - production
      - --hostname
      - 0.0.0.0
      - --port
      - "3003"
    environment:
      DATABASE_NAME: ${FEED_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672${RABBITMQ_VHOST}
      SERVICE_PORT: ${FEED_SERVICE_PORT}
    ports:
      - "${FEED_SERVICE_PORT}:3003"

  notifications-service:
    <<: *common-vars
    build:
      context: ./services/notifications-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    command:
      - /run/NotificationsService
      - serve
      - --env
      - production
      - --hostname
      - 0.0.0.0
      - --port
      - "3004"
    environment:
      DATABASE_NAME: ${NOTIFICATIONS_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672${RABBITMQ_VHOST}
      SERVICE_PORT: ${NOTIFICATIONS_SERVICE_PORT}
    ports:
      - "${NOTIFICATIONS_SERVICE_PORT}:3004"

volumes:
  postgres_data:
