version: '3.8'

x-common-vars: &common-vars
  env_file:
    - .env

services:
  postgres:
    <<: *common-vars
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${IDENTITY_DB},${PLANTS_DB},${FEED_DB},${GATEWAY_DB},${NOTIFICATIONS_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    <<: *common-vars
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"  # Management UI

  api-gateway:
    <<: *common-vars
    environment:
      DATABASE_NAME: ${GATEWAY_DB}
      IDENTITY_SERVICE_URL: http://identity-service:3001
      PLANTS_SERVICE_URL: http://plants-service:3002
    ports:
      - "${API_GATEWAY_PORT}:80"

  identity-service:
    <<: *common-vars
    environment:
      DATABASE_NAME: ${IDENTITY_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672${RABBITMQ_VHOST}
